### ISSUE TITLE
Menu controls don't map properly

### ISSUE THREAD

**Issue by RunninPigeon** [JHDev2006/Super-Mario-Bros.-Remastered-Public#230]
**Describe the bug**

**To Reproduce**
1. Go to menu and rebind keys

**Expected behavior**
Menu buttons switch with keys.

**Comment by mrTerryBogard** [comment]
I confirm. The controller is assigned and works. The keyboard is only assigned and doesn't work in the menu. At least I tried the Num Pad.

**Comment by pnaw10** [comment]
Also confirming.  This looks like a great effort, but when I go to settings to try to map my Gravis GamePad Pro, I can map to DPAD L and DPAD D, but it acts as if my DPAD R and DPAD U buttons don't exist.  When I go to the controller settings in Windows, it confirms the joypad works properly in all directions and all 10 of the other buttons work as intended, so this appears to be specific to the SMB Remastered software.

**Comment by JeodC** [comment]
This is resolved and will be in v1.0.2.

**Comment by pnaw10** [comment]
Nope, still doesn't work.  
Windows controller settings confirm that all Gravis GamePad buttons work properly.
SMBR still only recognizes DPAD L and DPAD D and it still ignores any presses of DPAD R and DPAD U.

Since I can't reopen this one, I filed a new issue --  #709.
